name: Docker Unleash

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image with Date
      run: docker build . --file Dockerfile --tag unleash-task:$(date +%s)

    - name: Test Docker Image
      run: |
        docker run -d -e BUCKET_NAME=${{ secrets.BUCKET_NAME }} --name unleash-task unleash-task:latest
        sleep 10 
        if docker ps | grep unleash-task; then
          echo "Container started successfully"
        else
          echo "Container failed to start"
          exit 1
        fi

    - name: Stop and remove the Docker container
      run: |
        docker stop unleash-task
        docker rm unleash-task


        
