name: Docker Unleash

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Everything:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag unleash-task:latest

    - name: Test Docker Image
      run: |
        docker run -d -e BUCKET_NAME=test-bucket --name unleash-task unleash-task:latest
        sleep 10
        docker logs unleash-task
        if docker ps | grep unleash-task; then
          echo "Container started successfully"
        else
          echo "Container failed to start"
          exit 1
        fi

    - name: Stop and remove the Docker container
      run: |
        docker stop unleash-task
        docker rm unleash-task

    - name: Pulumi Set-up
      uses: pulumi/actions@v5
      with:
        stack-name: Unleash
        work-dir: ./pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2  # Replace with your desired region
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}

    - name: Pulumi Preview
      run: |
        pwd
        ls
        pulumi preview        


